### ISSUE TITLE
[MELHORIA] Otimização de uso da nuvem

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/Estacao-Trabalho-CMC#124]
## Descrição

Foi escolhido utilizar a funcionalidade via Webdav, porém o mesmo trouxe problemas de lentidão.

### A sua melhoria está relacionada com um problema? Por favor descreva

Por algumas vezes foi relatado o travamento no momento de exibir os arquivos contidos na nuvem, mesmo que já houvesse sido feita uma "sincronização do serviço"

### Descreva a solução que você gostaria

Solucionar o problema de lentidão.

### Descreva as alternativas que você considerou

Se existem múltiplas soluções, por favor enumere-as e as descreva separadamente. Deixe comparações para depois da enumeração.

**Comment by brunosoli** [comment]
Mais referências:

- https://github.com/owncloud/core/issues/23649
- https://github.com/nextcloud/server/issues/8962
  Aparentemente este é um problema resolvido no nextcloud, mas talvez não seja o mesmo problema
- https://docs.cyberduck.io/protocols/webdav/nextcloud/?highlight=slow#
- https://help.nextcloud.com/t/webdav-extremely-slow-on-linux-using-davfs2-mount/123811

**Comment by diemello** [comment]
Existe previsão de migração dos arquivos para o AWS?
Visto que o Webdav funciona parcialmente a contento e até o momento não foram encontradas soluções definitivas para o problema de lentidão, sugiro que seja mantido o formato de acesso atual até a nova Nuvem.

**Comment by brunosoli** [comment]
Está no nosso top 3.
@sandroizumi está trabalhando nisso há algum tempo já, ele pode nos dar uma previsão.

**Comment by sandroizumi** [comment]
Estou resolvendo uns problemas que estão acontecendo na migração (arquivos, compartilhamento e banco). Acredito que semana vem, já posso dar uma previsão

**Comment by sandroizumi** [comment]
Definido na versão mais recente das estações de trabalho que o acesso aos arquivos somente se dará pela página web da Nuvem, não sendo mais necessária a resolução desse problema.
