### ISSUE TITLE
Troca do navegador padrão em todas as versões

### ISSUE THREAD

**Issue by tsocher** [CMCuritiba/Estacao-Trabalho-CMC#127]
## Descrição

Alteração de navegador padrão para o Chrome

### A sua melhoria está relacionada com um problema? Por favor descreva

Foi notado falhas no Firefox ao devolver a confirmação de login via SSO para o Zoom, desta forma o usuário não consegue logar-se novamente na ferramenta após logoff, porquê o 1º login funciona.

**Comment by sandroizumi** [comment]
Resolvido na última versão da imagem das estações de trabalho, não mais ocorrendo o problema.
