### ISSUE TITLE
Estudo de possível erro do LibreOffice com Webdav

### ISSUE THREAD

**Issue by tsocher** [CMCuritiba/Estacao-Trabalho-CMC#129]
### Arquivos que somem segundo alegações de usuários

Em alguns suportes atendidos, houve reclamações que se perdeu o arquivo sendo editado, ignorando possíveis falhas do usuário, esses arquivos estavam sempre em uso no LibreOffice com ETv5.

Ideia é ver se há um risco de perca de informações quando abre-se um arquivo no LibreOffice com a nuvem via Webdav e no processo ocorra uma falha em algum ponto.

Detalhe: Ao abrir o arquivo ocorre duas situações na nuvem. 1ª Com o arquivo aberto, outro usuário ao tentar abrir recebe a notificação que o arquivo está em uso, essa é de boa. 2ª Com o arquivo aberto, outro usuário não visualiza o arquivo mais no gerenciador enquanto o outro estiver usando, quando este fecha o arquivo ele volta a aparecer.

As duas situações são aleatórias quanto a sua ocorrência. Mas será que isso pode contribuir com esta questão?

**Comment by sandroizumi** [comment]
Não ocorreram mais problemas após realizar atualizações do Libreoffice e do Linux Mint. De qualquer forma, é importante a edição de arquivos estar bloqueada para mais de um usuário ao mesmo tempo, a fim de evitar conflitos. Para não ter risco de perda de informações, recomenda-se sempre a verificação e utilização da página web da Nuvem porque lá é mais válido para constatar a integridade dos arquivos, a última alteração dos mesmos, bem como se foram apagados.
