### ISSUE TITLE
Erro no áudio ETv5

### ISSUE THREAD

**Issue by tsocher** [CMCuritiba/Estacao-Trabalho-CMC#130]
## PC sem som em situações específicas

Já foram notadas várias vezes via suporte que:
- Usuário reclama que está sem som;
- No acesso remoto, nota-se que está sem o ícone de som e sem hardware na configuração de som;
- Via terminal, comando alsamixer também não funciona.

A solução paliativa:
- Remove-se o arquivo de configuração "pulse" do usuário e;
- Muda-se a senha da rede do usuário, e ao reinicar, o problema resolve-se.

**Comment by diemello** [comment]
Sabe se houve alguma instalação diferente nestas estações ou algo via script que possa ter mudado permissões?

**Comment by tsocher** [comment]
Nada diferente foi feito. O fato acontece no usuário, pensando agora, será que ele perde acesso ou permissão ao som?

**Comment by diemello** [comment]
Teria que pegar uma máquina que deu problema e analisar antes de efetuar a solução do problema.
Estou analisando códigos de alterações (daqui e da infra), mas até o momento nada que pareça ser o causador do problema.

**Comment by sandroizumi** [comment]
Problema ocorria com frequência naa versão do Linux Mint 20. Após atualizar a imagem para a versão 21.1 e instalar drivers mais recentes, não houveram mais ocorrências de perdas de áudio.
