### ISSUE TITLE
Firefox + Zoom

### ISSUE THREAD

**Issue by tsocher** [CMCuritiba/Estacao-Trabalho-CMC#131]
## Erro no retorno da requisição de login SSO para o Zoom somente via Firefox

O navegador foi modificado para padrão nas imagens pelo seguinte motivo:

Ao logar via SSO no Zoom, após a chamada para o navegador para digitar as credenciais, no Firefox, ao confirmar, ele pergunta com qual aplicação será aberto a requisição, escolhe-se o Zoom e dá-se sequência, abre o Zoom normalmente.

O problema ocorre ao fazer isto da segunda vez em diante, chega até a etapa de escolher o aplicativo que irá abrir após passo das credenciais e não chama o aplicativo Zoom.

No Chrome não ocorre e no Firefox em instalação limpa de Linux também não ocorre.

**Comment by sandroizumi** [comment]
O navegador Google Chrome foi definido como navegador padrão do sistema, então o Zoom executa o mesmo para autenticar o usuário, desta forma o problema foi corrigido.
