### ISSUE TITLE
Nuvem + ZIP

### ISSUE THREAD

**Issue by tsocher** [CMCuritiba/Estacao-Trabalho-CMC#132]
## Erro ao realizar download de pasta ou grupo de arquivos

Quando recebe-se um link compartilhado, geralmente faz-se o acesso via nuvem.cmc.pr.gov.br, ao optar pelo download de pasta ou grupo de arquivos, gera-se um ZIP, só que compactado fica corrompido ao fim do download.

Somente arquivos unitários ou ZIP previamente salvo na nuvem que não dão problemas para download.

**Comment by sandroizumi** [comment]
Problema corrigido na nova versão de Linux Mint das estações de trabalho, foram atualizados o sistema operacional e os navegadores Firefox e Chrome.
