### ISSUE TITLE
[MELHORIA] Atualizar código para autenticar ETs no AWS AD

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/Estacao-Trabalho-CMC#134]
## Descrição

Atualizar código para autenticar ETs no AWS AD.

### A sua melhoria está relacionada com um problema? Por favor descreva

Migração do serviço para a AWS.

### Descreva a solução que você gostaria

Instalar pacotes autenticação que permitam:

- [x] Join no domínio
- [x] Cache de login/senha
- [x] Permitir login e ssh com `uid`
  - [x] Login
  - [x] SSH
- [ ] Permitir sudo
- [x] Criar `home` do usuário no padrão já utilizado em produção
- [x] Permitir alteração senha expirada via tela de login do Mint
- [x] Mapear atributos e grupo principal (`gidNumber`)
- [x] Validar comandos `id`, `groups` e `getent`
- [x] Alterar nome de um PC
- [x] Pesquisa de nomes no domínio `cmc.pr.gov.br` (DNS)

### Descreva as alternativas que você considerou

Nenhuma

### Contexto adicional

Possíveis referências úteis:

- https://docs.aws.amazon.com/directoryservice/latest/admin-guide/join_linux_instance.html
- https://jumpcloud.com/blog/authenticating-linux-aws-directory-service

**Comment by brunosoli** [comment]
Mapear e listar configurações a serem realizadas na estação de trabalho.

**Comment by sandroizumi** [comment]
Pesquisa de nomes está pelo DNS do AD. Não resolve nomes do domínio cmc.pr.gov.br.

**Comment by brunosoli** [comment]
> Pesquisa de nomes está pelo DNS do AD. Não resolve nomes do domínio cmc.pr.gov.br.

Isso é o esperado. O domínio `cmc.pr.gov.br` será apenas para serviços na Internet (a ser resolvido pelo R53 na AWS).

**Comment by ewerton-dif** [comment]
Issue fechada porque o código foi transferido para CMCuritiba/iac-automacao#413 ao ser decidido que rodará no cmc-boot das ET e não nos scripts da instalação. Novas ET rodarão outros scripts para integração no AD definidos na issue #140
