### ISSUE TITLE
[MELHORIA] Atualizar Assinador Serpro

### ISSUE THREAD

**Issue by celsopedro** [CMCuritiba/Estacao-Trabalho-CMC#136]
## Inclusão da nova versão Assinador Serpro nas estações de trabalho

Estamos  com uma versão desatualiza, sendo aconselhável a atualização para a versão 4.0.2 do referido assinador

### Versão atual disponibilizada no link abaixo:

https://www.assinadorserpro.estaleiro.serpro.gov.br/downloads/

A versão atual funcionada perfeitamente, só foram adicionados algumas funcionalidades que alguns usuários usam.

### Descreva as alternativas que você considerou

Podemos simplentes executar o .deb nas estações e atualizar a medida que ocorrer a demanda.Inclusive nos principais 
setores como Projuris , RH e presidência isso já foi feito.Ficando a solucão acima  direcionada para os demais setores.

### Contexto adicional

Se atentar que no site existe  as versões homologação e produção.

**Comment by sandroizumi** [comment]
Criada issue no repositório da infraestrutura para resolução dessa demanda.

**Comment by sandroizumi** [comment]
CMCuritiba/infrastructure-automation#417
