### ISSUE TITLE
[MELHORIA] Migrar solução da nuvem para atualizar ET na ETV6.

### ISSUE THREAD

**Issue by gabriellisboaconegero** [CMCuritiba/Estacao-Trabalho-CMC#144]
## Descrição
Criar script que adiciona o serviço de atualização na nova estação de trabalho (ETV6).
Instalar `aws-cli` e chaves de segurança/acesso da aws.

### A sua melhoria está relacionada com um problema? Por favor descreva
O servidor nfs `/mnt/suporte` vai ser descontinuado e a partir da ETV6 ele não será montado na ET. Porém, a única forma de instalar o sincronizador, chaves de segurança AWS e aws-cli é se tiver montado `/mnt/suporte`. Vide https://github.com/CMCuritiba/iac-automacao/tree/issue509/ldap/etv4.

### Descreva a solução que você gostaria
- [ ] Script que instala o serviço `cmc-sincroniza-et.service`.
- [ ] Script que instala `aws-cli`.
  - [ ] Script que configura chaves de acesso ao bucket da AWS.

### Descreva as alternativas que você considerou
 - Algo semelhante ao script [`/mnt/suporte/boot.sh`](https://github.com/CMCuritiba/iac-automacao/blob/issue509/ldap/etv4/boot.sh.j2).

### Contexto adicional
N/A

**Comment by Lucas-PG** [comment]
Não há mais a necessidade da instalação do aws-cli ou do script cmc-sincroniza-et.service.

**Comment by brunosoli** [comment]
Código sendo adicionado no branch 137.
