### ISSUE TITLE
[BUG] Utilizar bluetooth pede senha de admin

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/Estacao-Trabalho-CMC#147]
## Descreva o bug

Detectados problemas com o bluetooth. Relato dos problemas:

1. Conectei no reloginho pra teste sem senha alguma ao ativar o Bluetooth e pra desativar pediu senha. O NB inicia com ele desligado, pra ligar não prede nada, para desligar senha ADM.
2. Sempre que faço login na máquina, como utilizo meu fone bluetooth, sempre aparece este aviso pedindo senha do suporte.

### Comportamento Esperado

Realizar conexões bluetooth sem utilizar senha de administrador.

### Sugira uma solução

Pesquisar a origem do problema e ajustar o SO para evitar a necessidade de senha no uso do bluetooth.

### Para Reproduzir

Vide relatos acime.

### Screenshots

![337916ca-d8e7-45fb-bd35-8c7233ef8b8c](https://github.com/CMCuritiba/Estacao-Trabalho-CMC/assets/7805168/0d88abbe-b5ca-4bcd-a56a-cdf78019d944)

![8007c32f-b97f-4ff9-9e87-9300f1e75a19](https://github.com/CMCuritiba/Estacao-Trabalho-CMC/assets/7805168/48c6513a-9015-4e1c-80d4-8769daf6aae4)

### Desktop (por favor preencha os campos abaixo)

- OS: Mint Cinnamon 21.3

### Contexto Adicional

Possíveis links de referência:

- https://linuxmint-user-guide.readthedocs.io/en/latest/bluetooth.html
- https://askubuntu.com/questions/1419667/ubuntu-setting-rfkill-state-requires-privileges
- https://warlord0blog.wordpress.com/2021/04/30/setting-rfkill-state-requires-authentication/

Possíveis configurações no `dconf` relacionadas:

```
org.blueman
org.blueman.general
org.blueman.gsmsettings
org.blueman.network
org.blueman.plugins.autoconnect
org.blueman.plugins.discvmanager
org.blueman.plugins.killswitch
org.blueman.plugins.netusages
org.blueman.plugins.powermanager
org.blueman.plugins.recentconns
org.blueman.plugins.serialmanager
org.blueman.transfer
```

**Comment by tsocher** [comment]
Ao clicar em habilitar ou desabilitar, pede-se com é normal senha adm, mas se deixar a tela de senha em aberto, após alguns minutos ela fecha e realiza o processo de habilitar ou desabilitar.

**Comment by sandroizumi** [comment]
Solução a ser adotada será a mesma que resolveu o problema de dispositivos USB.
Editar o arquivo _org.blueman.policy_ para retirar somente autorização de **admin** e permitir para todos os usuários.
