### ISSUE TITLE
Conexão LDAP para UCS

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/Estacao-Trabalho-CMC#30]
Alterar forma de configurar conexão com LDAP, UCS precisa de configuração específica.

Utilizar o Univention Domain Join Assistant
https://www.univention.com/products/univention-domain-join-assistant/
https://launchpad.net/~univention-dev/+archive/ubuntu/ppa

Testado o esquema acima com máquina virtual logando no https://ucs1.cmc.pr.gov.br

* Revisar o script 120-ldap_install.sh

**Comment by brunosoli** [comment]
Aparentemente o @joaopedrogalera conseguiu configurar a ET sem utilizar esse assistente.

**Comment by cpinheiro26** [comment]
1 - Instalado Mint 19.3 , apt-get update && upgrade, reboot após atualizar.
2 - Rodar script principal.sh (nesta data rodado a partir do Develop).
3 - Logar com seu usuário na rede normalmente. (Tauari) 

**Alterando dominio para o UCS**
4 - Rodar /mnt/suporte/etv4/ucs/ucs.sh , enter nos campos q pedir e mandar sobrescrever o pam na instalação.

5 - Apagar  o "/var/cache/nscd/passwd" (comando a ser incluido no ucs.sh) 

6 - Logar na rede normalmente (desde que o usuário tenha sido já importado do Tauari com UID e o campo "Display Name" setado como System User ).

**Comment by diemello** [comment]
Atualizado vendo necessidade de remover apenas os programas nscd nslcd e nss-update.

Incluido o script para atualização de estações de trabalho e solicitado testes atraves da issue [migracaoUnivention_issue_2](https://github.com/CMCuritiba/migracaoUnivention/issues/2)

**Comment by brunosoli** [comment]
O login offline funciona?

**Comment by diemello** [comment]
Foi Aberta issue [https://github.com/CMCuritiba/migracaoUnivention/issues/3](https://github.com/CMCuritiba/migracaoUnivention/issues/3) para verificação

**Comment by brunosoli** [comment]
Estamos avaliando as opções mas não usaremos o UCS.
Mas provavelmente o pacote de integração para login vai ser alterado para o sssd (conforme issue #98). Mas isso fica em suspenso até definição da solução.

Encerrando esta issue.
