### ISSUE TITLE
Operações de mover arquivos ao rodar os scritps

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/Estacao-Trabalho-CMC#56]
>> Erros de arquivos ausentes (principalmente em comandos do tipo mv). Que interrompem a execução e precisam ser verificados e adicionados no arquivo de exceções.

>> Sugere-se que seja feita uma verificação prévia se o arquivo existe antes de executar o comando.

>> talvez seja desejável que isto ocorra (essa parada por falta dos arquivos), contudo, sendo assim haverá mais trabalho ao rodar os scripts numa máquina que não tenha instalação fresh/clean e/ou em que já tenha sido rodado o script.

**Comment by sandroizumi** [comment]
Scripts revistos e resolvido o problema.
