### ISSUE TITLE
Instalar uma impressora apenas se ela não estiver instalada

### ISSUE THREAD

**Issue by lucaslm45** [CMCuritiba/Estacao-Trabalho-CMC#97]
**Descreva o bug**
Atualmente a impressora é reinstalada gerando a notificação "Impressora Adicionada" a cada 60 segundos.

**Para Reproduzir**
Passos para reproduzir o comportamento :
1. Instale o Linux Mint 20 Cinnamon
2. Baixe os arquivos do branch feature/UpMint
3. Rode como root o script principal.sh e reinicie a máquina
4. Faça login com algum usuário do LDAP
5. Veja o erro.

**Comportamento Esperado**
Instalar uma impressora apenas se não tiver nenhuma instalada.

**Desktop (por favor preencha os campos abaixo):**
 - OS: Linux Mint 20 Cinnamon
 
**Contexto Adicional**
Esse é o script que contém o serviço que roda a cada 60 segundos https://github.com/CMCuritiba/ETv4/blob/feature/UpMint/scripts/200-script-rede.sh

Uma alternativa pode ser bloquear a notificação de "Impressora Adicionada".

**Comment by brunosoli** [comment]
Como pode ser visto no script 200, o `boot.sh`, além do script de instalação de impressoras e outros, é montado remotamente.

É importante começar a versionar estes scripts. Alguma sugestão de nome/local? Algo como `scriptsRede` ou `rede` mesmo, na raiz do repositório?

**Comment by lucaslm45** [comment]
@brunosoli eu pensei em manter ele onde está com o nome configura-boot.

**Comment by brunosoli** [comment]
@lucaslm45, não entendi... o script não está no repositório.
Sugiro adicionar à raiz a seguinte estrutura:

```
./scriptsRede/
├── boot.sh
└── instala-impressora.sh
```

**Comment by lucaslm45** [comment]
Beleza, eu fiz algumas modificações nele, em outros scripts da mesma pasta e coloquei todos no branch feature/UpMint pra ser alterado depois.

**Comment by brunosoli** [comment]
IMHO, a criação de um `branch-97` pra poder incluir estes arquivos e fazer a correção do script é mais clara e simples do que embutir tudo no seu branch super featurizado.

**Comment by diemello** [comment]
Problema ocorre na ETV4 atual? 
Caso não ocorra podemos pausar e manter a issue para verificar após as alterações do script de instalação para cinnamon!

**Comment by Felipe-T-Oliveira** [comment]
> Problema ocorre na ETV4 atual?
> Caso não ocorra podemos pausar e manter a issue para verificar após as alterações do script de instalação para cinnamon!

Testei na ETv4 e funcionou!

**Comment by brunosoli** [comment]
O problema é que se o script `boot.sh` ou qualquer outro script executado por ele falhar, o systemd vai disparar o script novamente em 60 segundos. Hoje isso ocorre também nas ETs em produção. Ou seja, fica reinstalando as impressoras, fazendo "apt update" e outros comandos a cada 60 segundos.

O ponto levantado pelo @lucaslm45 é que no Cinnamon quando isso ocorre ele reinstala a impressora e aparece uma notificação do SO avisando sobre a impressora.

A questão é melhorar o script para evitar instalar se já estiver instalada e outra issue é corrigir bugs e tratar melhor os erros no script `boot.sh` e sub-scripts.

**Comment by sandroizumi** [comment]
Script de configuração do **cups** foi arrumado para evitar a redundância na instalação de impressoras. Também foi desabilitada a busca e instalação automática de impressoras através do script _configura-cups.sh_ na configuração do serviço _cups-browsed_.
