### ISSUE TITLE
[MELHORIA] Substituir libnss-ldapd e libpam-ldapd por sssd

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/Estacao-Trabalho-CMC#98]
## Descrição

Substituir a integração com LDAP para o pacote `sssd`.

### A sua melhoria está relacionada com um problema? Por favor descreva

O `sssd` é compatível com _domain joining_ utilizado por serviços como FreeIPA, UCS e AWS Directory Service, não contemplada pela configuração utilizada hoje.

### Descreva a solução que você gostaria

Configurar o `sssd` para:

- [x] Login local e via SSH
- [x] Conexão segura (LDAPS)
- [x] Bind obrigatório
- [x] Cache de login
- [x] Domain joining

### Descreva as alternativas que você considerou

Nenhuma.

### Contexto adicional

Aparentemente o `sssd` é a solução mais utilizada para integração com FreeIPA e AWS Directory Service e é utilizado no UCS client por baixo dos panos.

**Comment by sandroizumi** [comment]
#134

**Comment by sandroizumi** [comment]
Resolvido na nova versão da imagem das estações de trabalho.
